<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('products')->delete();
        DB::table('products')->insert([
            [
                'id'=>1,
                'name'=>'kengNam',
                'description'=>'kengNam',
                'categoryId'=>1,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>2,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>2,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>3,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>3,
                'price'=>2500,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>4,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>2,
                'price'=>2700,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>5,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>3,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>6,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>1,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>7,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>3,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>8,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>1,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>9,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>3,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>10,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>3,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>11,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>5,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>12,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>3,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>13,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>3,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>14,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>5,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>15,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>3,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>16,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>5,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>17,
                'name'=>'ơahihi',
                'description'=>'ahihi',
                'categoryId'=>3,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>18,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>3,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>19,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>4,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ],
            [
                'id'=>20,
                'name'=>'ahihi',
                'description'=>'ahihi',
                'categoryId'=>5,
                'price'=>2000,
                'image'=>'http://staticl.enternews.vn/images/big/pic1.png'
            ]
        ]);
    }
}
